version: '3.9'

services:
  rustapp:
    container_name: Rotondex
    image: PokedexRPGsql/0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://Pokedex:ALUMNO@localhost:5433/Rotondex
    ports:
      - '5433:5433'
    depends_on:
      - Rotondex
  db:
    container_name: Rotondex
    image: postgres:16
    environment:
      POSTGRES_USER: Pokedex
      POSTGRES_PASSWORD: ALUMNO
      POSTGRES_DB: Rotondex
    ports:
      - '5433:5433'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
